CREATE TABLE `上传` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `路径` VARCHAR(255) DEFAULT NULL,
  `user` VARCHAR(255) DEFAULT NULL,
  `date` VARCHAR(255) DEFAULT NULL,
  `stime` VARCHAR(255) DEFAULT NULL,
  `utime` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=690 DEFAULT CHARSET=utf8