CREATE TABLE `上传文件表` (
  `姓名` VARCHAR(10) DEFAULT NULL,
  `日期` VARCHAR(8) DEFAULT NULL,
  `文件` VARCHAR(500) DEFAULT NULL,
  `解压` VARCHAR(10) DEFAULT NULL,
  `录入时间` VARCHAR(100) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8
