CREATE TABLE `统计库` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `数据库名` VARCHAR(255) NOT NULL,
  `数据库用户名` VARCHAR(255) NOT NULL,
  `数据库密码` VARCHAR(255) NOT NULL,
  `user` VARCHAR(255) DEFAULT NULL,
  `tag` VARCHAR(255) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8